### ISSUE TITLE
Nuget 

### ISSUE THREAD

**Issue by igitur** [daxnet/irony#7]
Please push a build to Nuget. That will enable other libraries to use it too. The Myget feed works, but it's really complicated for users of my libraries that depend on this.

**Comment by daxnet** [comment]
Great suggestion, will do that as soon as I can.
Too busy these days on my job......

**Comment by sebastienros** [comment]
FYI I publish it myself here https://www.nuget.org/packages/Irony.Core/
But it's totally not an official one.

**Comment by igitur** [comment]
@sebastienros That's great. May I suggest that you add @daxnet as an owner on that package?

**Comment by daxnet** [comment]
@igitur @sebastienros I have pushed the packages to nuget by using my standard Jenkins job.

https://www.nuget.org/packages/Irony.NetCore/
https://www.nuget.org/packages/Irony.Interpreter.NetCore/

Please check if they work and let me know if we can close this ticket.

Thanks!

**Comment by igitur** [comment]
I can check only next week. Thanks for this.

**Comment by igitur** [comment]
Wait, now we have 2 versions by 2 maintainers? Why didn't you 2 consolidate?

**Comment by sebastienros** [comment]
I will remove mine, it was just because there was none available.

**Comment by daxnet** [comment]
@sebastienros Thanks a lot!
and @igitur Thank you for your nuget suggestion.

**Comment by sebastienros** [comment]
FYI, I am keeping my version around for now as I depend in it for Fluid and Orchard Core. I will point to the new one in the next weeks, then unlist it.

**Comment by igitur** [comment]
I've tested `Irony.NetCore` in my `XLParser` project and it works perfect. So from my side you can close.

**Comment by daxnet** [comment]
@igitur that is great!
Thanks!
