### ISSUE TITLE
Unable to open any of the .csproj files

### ISSUE THREAD

**Issue by Spartan322** [daxnet/irony#8]
The project files don't appear to be supported on my installation of VS 2015, when I open the solution I get:
```
<local-install>\irony\src\Irony\Irony.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  <local-install>\irony\src\Irony\Irony.csproj

<local-install>\irony\src\Irony.Interpreter\Irony.Interpreter.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  <local-install>\irony\src\Irony.Interpreter\Irony.Interpreter.csproj

<local-install>\irony\src\Irony.SampleApp\Irony.SampleApp.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  <local-install>\irony\src\Irony.SampleApp\Irony.SampleApp.csproj

<local-install>\Desktop\irony\src\Irony.Tests\Irony.Tests.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  <local-install>\Desktop\irony\src\Irony.Tests\Irony.Tests.csproj
```
It appears to have a similar problem on Xamarin Studio.

**Comment by daxnet** [comment]
@Spartan322 Are you able to have a try on VS2017?

**Comment by Spartan322** [comment]
I haven't bothered with VS2017, but I'll see about giving it a try.

**Comment by Spartan322** [comment]
Yeah, it works on VS2017, which is unfortunate because that seems to mean I can't use any other IDE to open the solution.

Edit: It's easy to get everything to work in other IDEs given the projects files get rebuilt. (you just miss the package details that VS2017 gives for example) Not exactly the most elegant thing to look at multiple error projects in the solution, but it seems to work fine enough (although any added files would then never be included by the original project files, and that can get messy)

**Comment by igitur** [comment]
The VS2017 project file format is the way forward. Get used to it sooner rather than later.

**Comment by Spartan322** [comment]
Well I guess my support of this project has to end here, I can't rely upon or use VS2017, bye then.

**Comment by sebastienros** [comment]
VsCode should work fine

**Comment by Spartan322** [comment]
The problem is I can't nor would like visual studio in my workflow.

**Comment by sebastienros** [comment]
VS Code != Visual Studio

https://code.visualstudio.com/

**Comment by Spartan322** [comment]
Unfortunately I'm pretty sure I can't manage that.

**Comment by igitur** [comment]
@spartan322 I'm curious. What is your preferred IDE then? In your original post you mentioned VS2015, but later you state you want to avoid VS.

**Comment by Spartan322** [comment]
I've used VS2015 to test C# project files for decent enough functionality and compatibility, my preferred IDE in C# is MonoDevelop/Xamarin Studio, which mostly coincides with VS2015 projects, only a few differences between their management of projects, and my workflow actually requires some of those differences. My avoidance of VS is also partly of preference to distance myself from Visual Studio for a lot of reasons.
